# On clarifie (encore) 
Afin de mettre en évidence le pouvoir de la clarification, je vous propose de remettre en place l'erreur de l'étape précédente : 

Nous avons donc le test suivant : 
```python
def test_calculate_sum_when_two_numbers():  
    assert calculate("10,20") == 29
```

Et le code suivant : 
```python
def calculate(expression):  
    if expression == "":  
        return 0  
    if expression == "10,20":  
        return 29  
    return int(expression)
```

Nos tests passent, mais nous savons que nous avons fait une erreur. Comment allons nous rendre compte de cette boulette ? 

Tout simplement en clarifiant.

Que représente ce `29` ? Si on relit nos règles métiers, `29`, c'est la somme de `20` et de `10`, que l'on retrouve dans la variable `expression`.

Clarifions : 
```python
def calculate(expression):  
    if expression == "":  
        return 0  
    if expression == "10,20":  
        return 10 + 20  
    return int(expression)
```

Et nous constatons que le test échoue : 
```
FAILED    [100%]
test_string_calculator.py:18 (test_calculate_sum_when_two_numbers)
30 != 29

Expected :29
Actual   :30
<Click to see difference>

def test_calculate_sum_when_two_numbers():
>       assert calculate("10,20") == 29
E       assert 30 == 29

test_string_calculator.py:20: AssertionError
```

Là, je n'ai plus le choix, je suis obligé de constater mon erreur. Il arrive de faire des erreurs lorsqu'on est dans la phase RED. Il arrive que l'on recopie cette erreur lorsqu'on est dans la phase GREEN. Mais si nous prenons le temps de clarifier, nous diminuons drastiquement le coût de ces erreurs car nous les détectons plus rapidement.

Corrigeons notre test et constatons que nous revenons dans la phase GREEN : 

```python
def test_calculate_sum_when_two_numbers():  
    assert calculate("10,20") == 30
```

Continuons à clarifier et découvrons la notion de baby-steps.
